/* eslint-disable @next/next/no-sync-scripts */
import { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';

export default function Document() {
	return (
		<Html>
			<Head>
				<title>Vition Studio - for youtuber</title>
				<meta name='description' content='Generated by create next app' />
				<script src='https://kit.fontawesome.com/fba3b48802.js'></script>
				<link rel='icon' href='/favicon2.ico' />
			</Head>
			<body>
				<Main />
				<NextScript />
				<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'></script>
			</body>
		</Html>
	);
}
